#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { renderDocument, siteURL, descriptions, docMetadata, escapeHTML: escape } = require('../docs.js');
const marked = require('../vendor/marked-12.0.2.min.js');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = path => readFileSync(resolve(root, path), 'utf8');

export function generateSite() {
  const manifest = JSON.parse(read('docs-manifest.json'));
  if (Object.keys(manifest.pages).sort().join() !== Object.keys(descriptions).sort().join()) {
    throw new Error('Every manifest page needs reviewed SEO metadata; remove obsolete entries too.');
  }
  const template = read('docs.html');
  const files = new Map();
  const urls = [siteURL];
  for (const [slug, page] of Object.entries(manifest.pages)) {
    const markdown = read(page.path);
    if (page.source && createHash('sha256').update(markdown).digest('hex') !== page.sha256) {
      throw new Error(`Snapshot hash mismatch: ${page.path}. Use the reviewed sync process.`);
    }
    const meta = docMetadata(slug, manifest);
    const source = page.source
      ? `https://github.com/${manifest.repository}/blob/${manifest.revision}/${page.source}`
      : `../${page.path}`;
    const label = page.source ? `Core source at ${manifest.revision.slice(0, 12)}` : 'Read Markdown source';
    const provenance = `<p class="docs-provenance"><a href="${escape(source)}">${escape(label)}</a>` +
      (page.source ? ' · Snapshot documentation; check sl-dbg version and --help for your installed release.' : '') + '</p>\n';
    const content = provenance + (page.note ? `<p>${escape(page.note)}</p>\n` : '') +
      renderDocument(markdown, marked, page, manifest);
    const metadata = [
      `<title>${escape(meta.title)}</title>`,
      `<meta name="description" content="${escape(meta.description)}" />`,
      `<link rel="canonical" href="${escape(meta.canonical)}" />`,
      `<meta property="og:type" content="article" />`,
      `<meta property="og:title" content="${escape(meta.title)}" />`,
      `<meta property="og:description" content="${escape(meta.description)}" />`,
      `<meta property="og:url" content="${escape(meta.canonical)}" />`,
      ...(!meta.indexable ? ['<meta name="robots" content="noindex,follow" />'] : [])
    ].join('\n  ');
    // Rewrite shell paths before inserting article links, which are already docs-relative.
    const html = template
      .replace(/<!-- documentation-metadata:start -->[\s\S]*?<!-- documentation-metadata:end -->/, () => metadata)
      .replace(/  <script src="[^"]+"><\/script>\n/g, '')
      .replace(/href="(?:docs\/([^"]+\.html)|(\.\/[^"]*)|style\.css)"/g,
        (_, doc, home) => `href="${doc || (home ? '../' + home.slice(2) : '../style.css')}"`)
      .replace(/<article id="content"[\s\S]*?<\/article>/,
        () => `<article id="content" class="docs-main" tabindex="-1">\n${content}    </article>`)
      .replace(`data-doc="${slug}"`, `data-doc="${slug}" class="active" aria-current="page"`);
    files.set(`docs/${slug}.html`, '<!-- Generated by scripts/generate-site.mjs; edit Markdown and the shared docs.html shell. -->\n' + html);
    if (meta.indexable) urls.push(meta.canonical);
  }
  files.set('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    urls.map(url => `  <url><loc>${escape(url)}</loc></url>`).join('\n') + '\n</urlset>\n');
  for (const name of readdirSync(resolve(root, 'docs')).filter(name => name.endsWith('.html'))) {
    if (!files.has(`docs/${name}`)) throw new Error(`Obsolete generated route docs/${name}; review and remove it.`);
  }
  return files;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length && args[0] !== '--check')) {
    throw new Error('Usage: node scripts/generate-site.mjs [--check]');
  }
  const check = args[0] === '--check';
  const files = generateSite();
  for (const [path, content] of files) {
    if (check) {
      if (read(path) !== content) throw new Error(`${path} is stale. Run node scripts/generate-site.mjs and commit the output.`);
    } else writeFileSync(resolve(root, path), content);
  }
  console.log(`${check ? 'Verified' : 'Generated'} ${files.size - 1} static documents and sitemap.xml.`);
}
